import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Toaster } from "@/components/ui/toaster";
import Link from "next/link";
import RightSidebar from "@/components/shared/RightSidebar";
import LeftSidebar from "@/components/shared/LeftSidebar";
import Topbar from "@/components/shared/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
        <body className={inter.className}>
          <Topbar/>
          <main className='flex flex-row'>
            <LeftSidebar />
              <section className='main-container'>
                <div className='w-full max-w-6xl'>
                  {children}
                </div>
              </section>
            {/* <RightSidebar /> */}
          </main>
        </body>
      </html>
	);
}
